// <auto-generated />
using ItemCustomerData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItemCustomerData.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    partial class DemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ItemCustomerData.Entities.CustomerMaster", b =>
                {
                    b.Property<string>("Customer_FName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Customer_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Customer_Phone")
                        .HasColumnType("int");

                    b.HasKey("Customer_FName");

                    b.ToTable("CustomerMasters");
                });

            modelBuilder.Entity("ItemCustomerData.Entities.ItemMaster", b =>
                {
                    b.Property<string>("Item_Name")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Item_Qty")
                        .HasColumnType("int");

                    b.Property<int>("Item_Rate")
                        .HasColumnType("int");

                    b.HasKey("Item_Name");

                    b.ToTable("ItemMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
